version: "3.7"
services:
  postgresql:
    image: postgres:13.2-alpine
    ports: ["192.168.99.100:5432:5432"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: [
      "postgres",
      "-c", "max_connections=1000",
      "-c", "synchronous_commit=off",
      "-c", "fsync=off",
      "-c", "full_page_writes=off",
      "-c", "max_wal_size=4GB",
      "-c", "checkpoint_timeout=30min"
    ]
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./config/database/pg_hba.conf:/usr/local/share/postgresql/pg_hba.conf
volumes:
  postgresqldata:
    external: false