default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: <%= ENV.fetch("POSTGRES_HOST") { 192.168.99.100 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: openplaces_development

test:
  <<: *default
  database: openplaces_test

production:
  <<: *default
  database: openplaces_production
